### ISSUE TITLE
Create Documentation for Wasabi 

### ISSUE THREAD

**Issue by amatya-aditya** [mihakralj/obsidian-cloudsync#3] opened 2024-12-27 20:18 UTC
I am new to cloud storage and noticed that Wasabi offers a one-month free trial. I'm interested in testing its compatibility with CloudSync. I attempted to follow the AWS setup instructions in the documentation, but was unsuccessful. I'm unsure if the same steps apply to Wasabi, and would greatly appreciate Wasabi-specific setup documentation.

I am getting this error.
S3 connection test failed {"success":false,"message":"S3 connection failed: Request failed, status 403","details":{"name":"Error","message":"Request failed, status 403","stack":"Error: Request failed, status 403\n at new t (app:/obsidian.md/app.js:1:1925609)\n at PU (app:/obsidian.md/app.js:1:1925801)\n at app:/obsidian.md/app.js:1:1926480\n at app:/obsidian.md/app.js:1:237228\n at Object.next (app:/obsidian.md/app.js:1:237333)\n at a (app:/obsidian.md/app.js:1:236051)"}}

**Comment by mihakralj** [comment] 2024-12-28 20:49
I will create Wasabi docs with screenshots, but the process is relatively straightforward:

- create a bucket with the name of your choosing: <BUCKET_NAME>
- when you create a bucket, you need to choose a deployment region
- - you lookup the [S3 endpoint for your region](https://docs.wasabi.com/docs/what-are-the-service-urls-for-wasabi-s-different-storage-regions): <ENDPOINT>
- you create a policy with access to your bucket (Obsidian_policy)
- you create a new user (service account) and assign it Obsidian_policy
- you generate keys for the created user: <ACCESS KEY>, <SECRET KEY>
- now you have all elements needed for CloudSync: BUCKET_NAME, ACCESS_KEY, SECRET_KEY, ENDPOINT

**Comment by amatya-aditya** [comment] 2024-12-29 05:58
Hi there! I tried following your documentation, but I'm having a little trouble getting it to work. I'm so sorry, this is my first time doing this! Would it be possible for you to create the Wasabi docs with screenshots? That would be super helpful. Thanks a bunch! ❤️

**Comment by mihakralj** [comment] 2024-12-30 05:30
here you go, let me know if you can follow it ok:
https://mihakralj.github.io/obsidian-cloudsync/#/wasabi

**Comment by amatya-aditya** [comment] 2024-12-30 07:03
Hey, thanks so much for the detailed instructions! I gave them a try, but I'm still having a bit of trouble getting it to work. I've tried a few times, even selecting different endpoints, but no luck so far. I'm not quite sure what's going on.

![image](https://github.com/user-attachments/assets/b332ea69-67cb-434e-a918-e7a0ce60944b)

**Comment by mihakralj** [comment] 2024-12-30 07:08
Turn on full debug in cloudsync settings and copy-paste the log. No keys or secrets are logged, so no worries that you are exposing too much.

**Comment by amatya-aditya** [comment] 2024-12-30 07:15
Yes, it began with `https://s3.us-west-1.wasabisys.com`, and I also tested other endpoints. I am located in Auburn, Alabama.

Here is the full debug log.

DEBUG
he initialized
DEBUG
Local vault manager initialized {"vault":"Grad Research - Obsidian","maxConcurrent":50}
DEBUG
Reading cache file
DEBUG
No cache file found, initializing empty cache
DEBUG
he initialized
DEBUG
Local vault manager initialized {"vault":"Grad Research - Obsidian","maxConcurrent":50}
DEBUG
ze initialized
DEBUG
Initialized AWS paths {"vaultPrefix":"Grad Research - Obsidian","normalized":"Grad Research - Obsidian"}
DEBUG
Initialized AWS paths {"vaultPrefix":"Grad Research - Obsidian","normalized":"Grad Research - Obsidian","encoded":"Grad Research - Obsidian","hex":"47726164205265736561726368202d204f6273696469616e"}
DEBUG
S3 manager initialized Grad Research - Obsidian
TRACE
Testing S3 connectivity
DEBUG
Validating S3 configuration
DEBUG
S3 configuration validated
DEBUG
Initializing S3 client
DEBUG
Cache directory created
DEBUG
S3 client configuration {"bucket":"obsidian-sync-aditya","endpoint":"https:/s3.us-west-1.wasabisys.com"}
DEBUG
S3 Connection Test - Starting
DEBUG
Calculating payload hash {"hasBody":false,"bodyType":"none","bodyLength":0}
DEBUG
Building canonical request {"method":"GET","originalPath":"obsidian-sync-aditya","encodedPath":"obsidian-sync-aditya","canonicalQuerystring":"list-type=2&max-keys=1&prefix=Grad%2520Research%2520-%2520Obsidian%2F"}
DEBUG
Canonical request built GET /obsidian-sync-aditya list-type=2&max-keys=1&prefix=Grad%2520Research%2520-%2520Obsidian%2F content-type:application/octet-stream host:s3.us-west-1.wasabisys.com x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 x-amz-date:20241230T071217Z content-type;host;x-amz-content-sha256;x-amz-date e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG
Canonical Request {"method":"GET","path":"obsidian-sync-aditya","queryParams":{"list-type":"2","max-keys":"1","prefix":"Grad Research - Obsidian"},"payloadHash":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","canonicalRequest":"GET\n/obsidian-sync-aditya\nlist-type=2&max-keys=1&prefix=Grad%2520Research%2520-%2520Obsidian%2F\ncontent-type:application/octet-stream\nhost:s3.us-west-1.wasabisys.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20241230T071217Z\n\ncontent-type;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}
DEBUG
Request Headers {"content-type":"application/octet-stream","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"20241230T071217Z","Authorization":"AWS4-HMAC-SHA256 Credential=YEIM97CHA67QEP6EEBP4/20241230/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=e69ae5e90b17173fbe677a7a7f20f2798732ca65c9751b49b2fcbd02571513a0"}
DEBUG
Making signed request {"url":"https:/s3.us-west-1.wasabisys.com/obsidian-sync-aditya?list-type=2&max-keys=1&prefix=Grad+Research+-+Obsidian%2F","method":"GET","headers":{"content-type":"application/octet-stream","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"20241230T071217Z","Authorization":"AWS4-HMAC-SHA256 Credential=YEIM97CHA67QEP6EEBP4/20241230/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=e69ae5e90b17173fbe677a7a7f20f2798732ca65c9751b49b2fcbd02571513a0"}}
ERROR
S3 Connection Test - Failed {"name":"Error","message":"Request failed, status 403","stack":"Error: Request failed, status 403\n at new t (app:/obsidian.md/app.js:1:1925609)\n at PU (app:/obsidian.md/app.js:1:1925801)\n at app:/obsidian.md/app.js:1:1926480\n at app:/obsidian.md/app.js:1:237228\n at Object.next (app:/obsidian.md/app.js:1:237333)\n at a (app:/obsidian.md/app.js:1:236051)"}
DEBUG
S3 connectivity test failed {"success":false,"message":"S3 connection failed: Request failed, status 403","details":{"name":"Error","message":"Request failed, status 403","stack":"Error: Request failed, status 403\n at new t (app:/obsidian.md/app.js:1:1925609)\n at PU (app:/obsidian.md/app.js:1:1925801)\n at app:/obsidian.md/app.js:1:1926480\n at app:/obsidian.md/app.js:1:237228\n at Object.next (app:/obsidian.md/app.js:1:237333)\n at a (app:/obsidian.md/app.js:1:236051)"}}
ERROR
S3 connection test failed {"success":false,"message":"S3 connection failed: Request failed, status 403","details":{"name":"Error","message":"Request failed, status 403","stack":"Error: Request failed, status 403\n at new t (app:/obsidian.md/app.js:1:1925609)\n at PU (app:/obsidian.md/app.js:1:1925801)\n at app:/obsidian.md/app.js:1:1926480\n at app:/obsidian.md/app.js:1:237228\n at Object.next (app:/obsidian.md/app.js:1:237333)\n at a (app:/obsidian.md/app.js:1:236051)"}}

**Comment by mihakralj** [comment] 2024-12-30 16:00
This shows some odd things, especially mismatch of endpoint and region...

Can you execute a simple python scripts? It will test that access credentials you use are valid - it should list the created buckets in the region (in this case us-west-1)

Let me know what you get as a result - should tell us if your keys are ok (at least to read), and if you did create a bucket in us-west-1 region of Wasabi storage.

```
import boto3

aws_access_key_id = 'YOUR_ACCESS_KEY'
aws_secret_access_key = 'YOUR_SECRET_KEY'
aws_endpoint = 'https://s3.us-west-1.wasabisys.com'

session = boto3.Session(aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, aws_session_token=None)
print(f"{session.client('s3', endpoint_url=aws_endpoint).list_objects_v2(Bucket=bucket_name)}")
```

If everything works right, response should look something like:

```
[{'Name': 'obsidiantest', 'CreationDate': datetime.datetime(2024, 12, 30, 0, 34, 30, 770000, tzinfo=tzutc())}]
```

**Comment by amatya-aditya** [comment] 2024-12-30 18:29
Okay, so I tried creating a bucket in the `us-east-1` region again. Then, I updated the policy to make sure the bucket name was right and gave it another go, but it still didn't work.

I tweaked the Python code a little bit – I added `bucket-name.` – and ran it.

```
import boto3
aws_access_key_id = 'YOUR_ACCESS_KEY'
aws_secret_access_key = 'YOUR_SECRET_KEY'
aws_endpoint = 'https://s3.us-east-1.wasabisys.com'
bucket_name = "obsidian-sync-gradresearch"

session = boto3.Session(aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, aws_session_token=None)
print(f"{session.client('s3', endpoint_url=aws_endpoint).list_objects_v2(Bucket=bucket_name)}")
```

I received the following output

`{'ResponseMetadata': {'RequestId': '268F9C1B3BB5D48F:A', 'HostId': 'i777ztXjgJoA31DWSdYMvmQo5hVQxMvdViSCssWDTyb4tD4Jh9amxOz3zwmQGXiT/ThtWytakT2u', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/xml', 'date': 'Mon, 30 Dec 2024 18:21:36 GMT', 'server': 'WasabiS3/7.21.4956-2024-11-19-46c524f579', 'x-amz-bucket-region': 'us-east-1', 'x-amz-id-2': 'i777ztXjgJoA31DWSdYMvmQo5hVQxMvdViSCssWDTyb4tD4Jh9amxOz3zwmQGXiT/ThtWytakT2u', 'x-amz-request-id': '268F9C1B3BB5D48F:A', 'x-wasabi-cm-reference-id': '1735582894907 38.27.106.102 ConID:1261409474/EngineConID:12221067/Core:2', 'transfer-encoding': 'chunked'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'obsidian-sync-gradresearch', 'Prefix': '', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 0}`

**Comment by mihakralj** [comment] 2024-12-30 18:52
So, you name bucket as obsidian-sync-gradresearch but I see in requests that we are trying to get to bucket obsidian+sync+gradresearch

Can you make a bucket that has name without special characters (spaces, dashes)? I think that might be the root cause based on what your python script returned and what I see in debug logs above

**Comment by amatya-aditya** [comment] 2024-12-30 19:16
Ah, it turns out the issue wasn't the bucket name after all! It was those sneaky spaces in my Obsidian vault name that were causing the problem. But hey, good news – I finally got the S3 connection working!

**Comment by mihakralj** [comment] 2024-12-30 19:38
so, bucket name was fine but vault name caused the issue? Vault name had spaces in the name?
Or both?

Let me know what do I need to change in the code - guarding the malformed BUCKET name or malformed VAULT names?

**Comment by amatya-aditya** [comment] 2024-12-30 19:50
the vault name had spaces in it! And the bucket name, while it didn't have spaces, had dashes, which I removed. I made both of those changes at the same time, and it worked for me! I didn't test each change individually, just did them together.

**Comment by mihakralj** [comment] 2024-12-30 20:45
Ok, let me work separately on each and change the code for future release.

Thanks for bug bashing! 👍

**Closed as completed** 2024-12-31 05:54 UTC
